stages:
  - test
  - sync

variables:
  GIT_DEPTH: 0

sync_to_github:
  stage: sync
  image: alpine:latest
  only:
    refs:
      - tags
  before_script:
    - apk add --no-cache git
    - git config --global user.name "GitLab CI"
    - git config --global user.email "ci@laessoe.net"
    - git config --global credential.helper store
    - echo "https://kasperlaessoe:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
  script: |
    git fetch origin
    git remote add github https://github.com/kasperlaessoe/aoc.git
    git checkout master
    git checkout -B to_github
    git reset --soft $(git rev-list --max-parents=0 HEAD)
    git commit -m "Squashed release from master: ${CI_COMMIT_TAG}"
    git push -f github to_github:main

test_aoc_2024:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0
  script:
    - cd 2024
    - dotnet restore
    - dotnet build --configuration Release
    - dotnet test --configuration Release --logger "junit" --results-directory TestResults
  artifacts:
    when: always
    paths:
      - 2024/bin/
      - 2024/TestResults/
    reports:
      junit: 2024/TestResults/TestResults.xml
    expire_in: 1 week
  only:
    refs:
      - master
      - merge_requests
      - tags
